---
 - name: Install Apache HTTP Server
   yum:
     name: httpd
     state: present

 - name: Start Apache service
   service:
     name: httpd
     state: started

 - name: Enable Apache to start on boot
   service:
     name: httpd
     enabled: yes

 - name: Copy index.html to web root
   copy:
     src: files/index.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: '0644'
